#requires -Version 5.1
# Run from the repository root: powershell -NoProfile -File tools/tgs_scripts/tests/ExternalRsc.Tests.ps1
$ErrorActionPreference = 'Stop'
. (Join-Path $PSScriptRoot '../ExternalRsc.ps1')
$fixtureRoot = Join-Path ([IO.Path]::GetFullPath((Join-Path $PSScriptRoot '../../..'))) "data/external-rsc-tests-$([guid]::NewGuid().ToString('N'))"
$null = New-Item -ItemType Directory -Path $fixtureRoot
$script:passed = 0
function Assert($Condition, [string]$Message) {
    if (!$Condition) { throw "FAIL: $Message" }
    $script:passed++
}

# Published AWS SigV4 vectors, not signatures generated by this implementation.
# https://docs.aws.amazon.com/AmazonS3/latest/developerguide/sig-v4-header-based-auth.html
$credentials = [pscustomobject]@{ AccessKeyId = 'AKIAIOSFODNN7EXAMPLE'; SecretAccessKey = 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY' }
$settings = [pscustomobject]@{ Bucket = 'examplebucket'; Region = 'us-east-1'; Prefix = 'external-rsc/test/' }
$date = [datetime]::Parse('2013-05-24T00:00:00Z').ToUniversalTime()
$headers = Get-S3Headers $settings $credentials GET '/test.txt' '' (Get-Sha256 '') @{ host = 'examplebucket.s3.amazonaws.com'; range = 'bytes=0-9' } $date
Assert ($headers.Authorization.EndsWith('f0e8bdb87c964420e857bd35b5d6ed310bd44f0170aba48dd91039c6036bdb41')) 'AWS GET signing vector'
$headers = Get-S3Headers $settings $credentials GET '/' 'max-keys=2&prefix=J' (Get-Sha256 '') @{ host = 'examplebucket.s3.amazonaws.com' } $date
Assert ($headers.Authorization.EndsWith('34b48302e7b5fa45bde8084f4b7868a86f0a534bc59db6670ed5711ef69dc6f7')) 'AWS query signing vector'
$headers = Get-S3Headers $settings $credentials PUT '/test%24file.text' '' '44ce7dd67c959e0d3524ffac1771dfbba87d2b6b4b4e99e42034a8b803f8b072' @{
    host = 'examplebucket.s3.amazonaws.com'; date = 'Fri, 24 May 2013 00:00:00 GMT'; 'x-amz-storage-class' = 'REDUCED_REDUNDANCY'
} $date
Assert ($headers.Authorization.EndsWith('98ad721746da40c64f1a55b78f14c238d841ea1380cd77a1b5971af0ece108bd')) 'AWS PUT signing vector'

# Live DreamDaemon holds the RSC open for writing; ordinary Get-FileHash fails.
$sharedRsc = Join-Path $fixtureRoot 'shared.rsc'
$sharedZip = Join-Path $fixtureRoot 'shared.zip'
[IO.File]::WriteAllText($sharedRsc, 'fixture-rsc-payload')
$writer = [IO.File]::Open($sharedRsc, [IO.FileMode]::Open, [IO.FileAccess]::ReadWrite, [IO.FileShare]::ReadWrite)
try {
    Assert ((Get-RscMd5 $sharedRsc) -ceq 'b3bccb5fc1654eabbc5033081c033ce4') 'hash RSC while DreamDaemon-style writer handle is open'
    New-RscZip $sharedRsc $sharedZip
    Assert ((Get-ZipRscHash $sharedZip) -ceq 'b3bccb5fc1654eabbc5033081c033ce4') 'package live RSC with shared read access'
} finally { $writer.Dispose() }

# Preserve every other config byte, including BOMs and newline conventions.
foreach ($bom in @($false, $true)) {
    foreach ($newline in @("`n", "`r`n")) {
        $file = Join-Path $fixtureRoot 'resources.txt'
        $encoding = New-Object Text.UTF8Encoding($bom)
        $other = "# resource comment${newline}ASSET_TRANSPORT webroot${newline}ASSET_CDN_URL https://assets.invalid/${newline}#EXTERNAL_RSC_URLS http://disabled.invalid/${newline}"
        [IO.File]::WriteAllText($file, "EXTERNAL_RSC_URLS http://old.invalid/${newline}${other}  external_rsc_urls http://other.invalid/", $encoding)
        Set-ResourceUrl $file 'http://new.invalid/tgstation.zip'
        Assert ([IO.File]::ReadAllText($file) -ceq "EXTERNAL_RSC_URLS http://new.invalid/tgstation.zip${newline}$other") 'replace rotating URLs, preserve browser settings'
        Set-ResourceUrl $file ''
        $actual = [Convert]::ToBase64String([IO.File]::ReadAllBytes($file))
        $expected = [Convert]::ToBase64String([byte[]]($encoding.GetPreamble() + $encoding.GetBytes($other)))
        Assert ($actual -ceq $expected) 'fallback preserves all unrelated bytes'
    }
}

function New-Fixture([string]$Name) {
    $root = Join-Path $fixtureRoot $Name
    $deploy = Join-Path $root 'Game/build'
    $config = Join-Path $root 'Configuration'
    $resources = Join-Path $config 'GameStaticFiles/config/resources.txt'
    $null = New-Item -ItemType Directory -Path $deploy, (Split-Path $resources), (Join-Path $config 'Secrets')
    [IO.File]::WriteAllText((Join-Path $deploy 'tgstation.rsc'), 'fixture-rsc-payload')
    [IO.File]::WriteAllText($resources, "EXTERNAL_RSC_URLS http://stale.invalid/`nASSET_TRANSPORT webroot`nASSET_CDN_URL https://assets.invalid/`n")
    @{ Enabled = $true; Bucket = 'examplebucket'; Region = 'us-west-1'; Prefix = 'external-rsc/test/' } | ConvertTo-Json | Set-Content (Join-Path $config 'external-rsc.json')
    @{ AccessKeyId = 'fixture'; SecretAccessKey = 'fixture' } | ConvertTo-Json | Set-Content (Join-Path $config 'Secrets/external-rsc-aws.json')
    [pscustomobject]@{ Root = $root; Deploy = $deploy; Resources = $resources; Config = $config }
}

$script:uploadFails = $false
$script:downloadFails = $false
$script:pruneFails = $false
$script:readOnlyVerify = $false
$script:events = @()
$script:publishedZip = Join-Path $fixtureRoot 'uploaded.zip'
function Invoke-S3($Settings, $Credentials, $Method, $Key, $Query, $File, $Headers) {
    if ($Method -eq 'PUT') {
        $script:events += 'upload'
        Assert (!(Select-String -LiteralPath $script:fixture.Resources -Pattern '^EXTERNAL_RSC_URLS')) 'URL absent before upload completes'
        if ($script:uploadFails) { throw 'fixture upload failure' }
        Copy-Item -LiteralPath $File -Destination $script:publishedZip -Force
        Assert ($Headers['x-amz-acl'] -eq 'public-read') 'public-read upload'
        Assert ($Headers['cache-control'] -eq 'public,max-age=31536000,immutable') 'immutable hash URL cache policy'
        return ''
    }
    if ($script:pruneFails) { throw 'fixture pruning failure' }
    '<ListBucketResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><IsTruncated>false</IsTruncated></ListBucketResult>'
}
function Test-PublicResource($Url, $RscHash, $ZipBytes, $DownloadFile) {
    $script:events += 'verify'
    Assert ($Url.StartsWith('http://')) 'anonymous verification uses HTTP'
    if (!$script:readOnlyVerify) {
        Assert (!(Select-String -LiteralPath $script:fixture.Resources -Pattern '^EXTERNAL_RSC_URLS')) 'URL absent before verification completes'
    }
    if ($script:downloadFails) { throw 'fixture downloaded hash mismatch' }
    Assert ((Get-ZipRscHash $script:publishedZip) -ceq $RscHash) 'ZIP contains exact rsc at root'
    Assert ((Get-Item $script:publishedZip).Length -eq $ZipBytes) 'published ZIP length matches'
}

$script:fixture = New-Fixture 'success'
Assert ((Invoke-ExternalRsc Publish $fixture.Deploy $fixture.Root) -eq 0) 'successful publish exit'
Assert (($script:events -join ',') -eq 'upload,verify') 'upload then verify'
$manifest = Get-Content (Join-Path $fixture.Deploy 'external-rsc-build.json') -Raw | ConvertFrom-Json
Assert ([IO.File]::ReadAllText($fixture.Resources).Contains("EXTERNAL_RSC_URLS $($manifest.url)")) 'URL published after verification'
Assert (@(Get-ChildItem $fixture.Deploy -Filter '*.zip').Count -eq 0) 'temporary ZIPs cleaned'
Assert (@(Get-ChildItem $fixture.Deploy -Directory -Filter 'external-rsc-*').Count -eq 0) 'staging directory cleaned'
function curl.exe { $global:LASTEXITCODE = 0; 'HTTP/1.1 200 OK' }
$script:readOnlyVerify = $true
$beforeVerify = [IO.File]::ReadAllText($fixture.Resources)
Assert ((Invoke-ExternalRsc Verify $fixture.Deploy $fixture.Root) -eq 0) 'verification returns only numeric exit status, not curl headers'
Assert ([IO.File]::ReadAllText($fixture.Resources) -ceq $beforeVerify) 'verification is read-only'
$script:readOnlyVerify = $false
Set-ResourceUrl $fixture.Resources 'http://other-build.invalid/'
Assert ((Invoke-ExternalRsc Activate $fixture.Deploy $fixture.Root) -eq 0) 'activation exit'
Assert ([IO.File]::ReadAllText($fixture.Resources).Contains($manifest.url)) 'activation restores selected build URL'
[IO.File]::AppendAllText((Join-Path $fixture.Deploy 'tgstation.rsc'), 'changed')
Assert ((Invoke-ExternalRsc Activate $fixture.Deploy $fixture.Root) -eq 0) 'stale manifest does not fail activation'
Assert (!(Select-String $fixture.Resources -Pattern '^EXTERNAL_RSC_URLS')) 'stale manifest selects on-demand'

foreach ($failure in @('upload', 'download', 'credentials', 'settings', 'disabled', 'prune')) {
    $script:fixture = New-Fixture $failure
    $script:uploadFails = $failure -eq 'upload'
    $script:downloadFails = $failure -eq 'download'
    $script:pruneFails = $failure -eq 'prune'
    if ($failure -eq 'credentials') { [IO.File]::WriteAllText((Join-Path $fixture.Config 'Secrets/external-rsc-aws.json'), '{BROKEN-SECRET-CANARY') }
    if ($failure -eq 'settings') { [IO.File]::Delete((Join-Path $fixture.Config 'external-rsc.json')) }
    if ($failure -eq 'disabled') { '{"Enabled":false}' | Set-Content (Join-Path $fixture.Config 'external-rsc.json') }
    $messages = @()
    Assert ((Invoke-ExternalRsc Publish $fixture.Deploy $fixture.Root -WarningVariable +messages) -eq 0) "$failure does not fail deployment"
    Assert (($messages -join '') -notmatch 'BROKEN-SECRET-CANARY') 'credential parse errors do not reveal secrets'
    $hasUrl = !!(Select-String $fixture.Resources -Pattern '^EXTERNAL_RSC_URLS')
    Assert ($hasUrl -eq ($failure -eq 'prune')) "$failure fallback/retained URL"
    Assert ([IO.File]::ReadAllText($fixture.Resources).Contains('ASSET_TRANSPORT webroot')) "$failure preserves browser settings"
    Assert (@(Get-ChildItem $fixture.Deploy -Filter '*.zip').Count -eq 0) "$failure temporary cleanup"
}

# Pruning must finish pagination before deleting anything, and only delete this prefix's ZIPs.
$script:deleted = @()
$script:page = 0
$keys = @(1..5 | ForEach-Object { 'external-rsc/test/tgstation-' + $_.ToString('x32') + '.zip' })
function Invoke-S3($Settings, $Credentials, $Method, $Key, $Query) {
    if ($Method -eq 'DELETE') {
        Assert ($script:page -eq 2) 'pagination completes before deletion'
        $script:deleted += $Key
        return ''
    }
    $script:page++
    Assert ($Query.prefix -eq 'external-rsc/test/tgstation-') 'list only instance ZIP prefix'
    if ($script:page -eq 1) { $indexes = @(0, 1, 2); $tail = '<IsTruncated>true</IsTruncated><NextContinuationToken>a+/=</NextContinuationToken>' }
    else {
        Assert ($Query['continuation-token'] -eq 'a+/=') 'pagination token retained'
        $indexes = @(3, 4); $tail = '<IsTruncated>false</IsTruncated>'
    }
    $contents = ($indexes | ForEach-Object { "<Contents><Key>$($keys[$_])</Key><LastModified>2026-09-0$($_ + 1)T00:00:00Z</LastModified></Contents>" }) -join ''
    "<ListBucketResult xmlns='http://s3.amazonaws.com/doc/2006-03-01/'>$contents<Contents><Key>unrelated.zip</Key><LastModified>2000-01-01T00:00:00Z</LastModified></Contents>$tail</ListBucketResult>"
}
Remove-OldResources $settings $credentials @($keys[0], $keys[4])
Assert (($script:deleted -join ',') -ceq ($keys[1..2] -join ',')) 'retain active, published, and newest third build; preserve unrelated objects'
Write-Host "PASS: $script:passed assertions. Fixtures: $fixtureRoot"
